AllCops:
  Exclude:
    - config/initializers/secret_token.rb
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*.rb
    - bin/setup
    - bin/spring
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - config/routes.rb
    - config/application.rb    
    - config/initializers/*.*
    - config/environments/*.*
    - Rakefile
    - Gemfile


Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20